### ISSUE TITLE
[[enrichments]>worker22] ruby - Ruby exception occurred: no implicit conversion of nil into String 

### ISSUE THREAD

**Issue by anubisg1** [Cargill/OpenSIEM-Logstash-Parsing#374]
## Describe the bug
```
[ERROR] 2022-11-26 07:54:05.540 [[enrichments]>worker14] ruby - Ruby exception occurred: no implicit conversion of nil into String {:class=>"TypeError", :backtrace=>["(ruby filter code):68:in `block in filter_method'", "org/jruby/RubyArray.java:1865:in `each'", "(ruby filter code):67:in `block in filter_method'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-filter-ruby-3.1.8/lib/logstash/filters/ruby.rb:96:in `inline_script'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-filter-ruby-3.1.8/lib/logstash/filters/ruby.rb:89:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:178:in `block in multi_filter'", "org/jruby/RubyArray.java:1865:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:175:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:134:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:301:in `block in start_workers'"]}
```

## X-Reference issues
_(Cross reference any user stories that this bug might be affecting)_

## Steps To Reproduce
start the enrichment pipeline. I'm using logstash 8.5.2

## Expected behavior
no error should  be seen

## Additional context
The following components in enrichment make use of ruby filer, but i don't understand what is the culprit

```
./02_ecs_data_type.conf
./04_timestamp.conf
./11_related_hosts.conf
./12_related_user.conf
./13_related_ip.conf
./14_related_hash.conf
./16_related_mac.conf
./93_mitre.conf
./94_remove_empty_n_truncate.conf
```

**Comment by anubisg1** [comment]
looking at the tags, i see `enrichment_remove_empty_ruby_exception"` which indicates the problem is 94_remove_empty_n_truncate.conf

**Comment by KrishnanandSingh** [comment]
Yes, that's right. It is caused by `enrichment_remove_empty_ruby_exception` but the only problem is, it is not reproducible and so I can raise bug with logstash-plugin developers. I guess something is wrong with the ruby plugin rather than the code.

**Comment by anubisg1** [comment]
i'm wondering if this has anything to do with 
```
  pipeline.batch.delay: 50
  pipeline.batch.size: 1000
  pipeline.workers: 64
```

i noticed that if i send 1 document, i get no errors, but if i send multiple documents (the same one, repeated multiple times), then i get this error once or twice ...

**Comment by KrishnanandSingh** [comment]
@anubisg1 you are right about this behaviour. It happens only under load. 

Recently I disabled the noise from such exceptions by filtering them out with logstash's log4j.properties
```
rootLogger.filter.implicitConversionNoise.type = RegexFilter
rootLogger.filter.implicitConversionNoise.regex = Ruby exception occurred: no implicit conversion of nil into String .*
rootLogger.filter.implicitConversionNoise.onMatch = DENY
rootLogger.filter.implicitConversionNoise.onMismatch = NEUTRAL
```

And that is when I saw meaningful errors like:
```
[2023-10-30T13:07:12,474][ERROR][logstash.filters.ruby    ][enrichments][de98039f96d2dd586a96dd87f13c75d98698e247ca3a7ecfe993b333df11fb7c] Ruby exception occurred: Detected invalid array contents due to unsynchronized modifications with concurrent users {:class=>"ConcurrencyError", :backtrace=>["org/jruby/RubyArray.java:1347:in `<<'", "(ruby filter code):60:in `block in walk_hash'", "org/jruby/RubyHash.java:1519:in `each'", "(ruby filter code):58:in `walk_hash'", "(ruby filter code):59:in `block in walk_hash'", "org/jruby/RubyHash.java:1519:in `each'", "(ruby filter code):58:in `walk_hash'", "(ruby filter code):59:in `block in walk_hash'", "org/jruby/RubyHash.java:1519:in `each'", "(ruby filter code):58:in `walk_hash'", "(ruby filter code):59:in `block in walk_hash'", "org/jruby/RubyHash.java:1519:in `each'", "(ruby filter code):58:in `walk_hash'", "(ruby filter code):66:in `block in filter_method'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-filter-ruby-3.1.8/lib/logstash/filters/ruby.rb:96:in `inline_script'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-filter-ruby-3.1.8/lib/logstash/filters/ruby.rb:89:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:178:in `block in multi_filter'", "org/jruby/RubyArray.java:1865:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:175:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:133:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:304:in `block in start_workers'"]}
```

After a little bit of searching I stumbled upon https://github.com/logstash-plugins/logstash-filter-ruby/blob/main/docs/index.asciidoc#avoiding-concurrency-issues

Updated the code and viola! it was gone.

Thank you for your patience.
